version: 2.1

# We use CIRCLE_COMPARE_URL to halt redundant jobs
# Saving you time, and in turn TONS in runtime costs
# To make this happen, we need this orb to construct the URL
# (there are outstanding issues with the URL being blank, circa Q1 2019)
# https://github.com/iynere/compare-url
orbs:
  compare-url: iynere/compare-url@0.4.10


# === COMMANDS ===
commands:
  halt_if_unchanged:
    description: "Halt run if source files haven't been changed"
    parameters:
      directories:
        description: "Directories to check for changes, separated by spaces"
        type: string
        default: "client"
    steps:
      - compare-url/reconstruct
      - run:
          # https://github.com/iynere/compare-url#command-example
          name: Halt if unchanged based upon git commit range in CIRCLE_COMPARE_URL
          command: |
            # Load the compare URL, since this is a fresh shell
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)
            # Run the check-changes script
            cd ~/repo
            sh .circleci/check-changes.sh "${CIRCLE_COMPARE_URL}" "<< parameters.directories >>" || circleci step halt

# === JOBS ===
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: production
    working_directory: ~/repo/client
    steps:
      - checkout:
          path: ~/repo
      - halt_if_unchanged:
          directories: "client"
      - restore_cache:
          keys:
            - v1-repo-build-{{ checksum "package-lock.json" }}
            - v1-repo-build-
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - save_cache:
          key: v1-repo-build-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run: 
          name: Static Build
          command: CI=false npm run build
  unit:
    docker:
      - image: circleci/node:10
        environment:
          CYPRESS_INSTALL_BINARY: 0 # Skips cypress installation
    working_directory: ~/repo/client
    steps:
      - checkout:
          path: ~/repo
      - halt_if_unchanged:
          directories: "client"
      - restore_cache:
          keys:
            - v1-repo-unit-{{ checksum "package-lock.json" }}
            - v1-repo-unit-
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - save_cache:
          key: v1-repo-build-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run: 
          name: Test w/ Jest
          command: npm run test
  e2e:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      # - halt_if_unchanged:
      #     directories: "client e2e"
      - restore_cache:
          keys:
            # https://medium.com/@chrisbanes/circleci-cache-key-over-many-files-c9e07f4d471a
            - v1-repo-e2e-{{ checksum "e2e/package-lock.json" }}-{{ checksum "client/package-lock.json" }}-{{ checksum "package-lock.json" }}
            - v1-repo-e2e
      # TODO: Refactor server root directory...
      - run:
          name: Install Dependencies
          command: 
            |
              npm --version
              cd ~/repo/e2e && npm ci --no-audit
              cd ~/repo/client && npm ci --no-audit
              npm ci --no-audit
      - save_cache:
          key: v1-repo-e2e-{{ checksum "e2e/package-lock.json" }}-{{ checksum "client/package-lock.json" }}-{{ checksum "package-lock.json" }}
          paths:
            # cache NPM modules and the folder with the Cypress binary
            - ~/.npm
            - ~/.cache
            # cache individual folders
            - ~/repo/e2e/node_modules
            - ~/repo/client/node_modules
            - ~/repo/node_modules
      - run:
          name: Static Build
          command: cd client && CI=false npm run build
      - run:
          name: Start Server (fullstack)
          command: npm run start
          background: true
      - run:
          name: Cypress Testing
          command: $(npm bin)/cypress run --reporter junit --reporter-options "mochaFile=junit-results/my-test-output.xml" --config video=true
      - store_artifacts:
          path: ~/repo/e2e/cypress/screenshots
          when: on_fail
      - store_artifacts:
          path: ~/repo/e2e/cypress/videos
          when: on_fail
      - store_artifacts:
          path: ~/repo/e2e/junit-results
      - store_test_results:
          path: ~/repo/e2e/junit-results
  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: SCP code to EC2 instance
          command: scp -r -o StrictHostKeyChecking=no ~/repo ubuntu@54.184.122.185:/home/repo/
      - run:
          name: Deployment Script
          command: ssh -o StrictHostKeyChecking=no ubuntu@54.184.122.185 "~/repo/.circleci/deploy.sh"
      # - run:
      #     name: NOW_TOKEN Exists in CircleCI Dashboard
      #     command: if [ -z ${NOW_TOKEN+x} ]; then exit 0; fi
      # - run:
      #     name: Install Dependencies
      #     command: npm i -g now
      # - run:
      #     name: Deploy w/ Now
      #     command: now -t ${NOW_TOKEN}
            # - now -t ${NOW_TOKEN} alias foo
# === WORKFLOWS ===
workflows:
  full_stack:
    jobs:
      - e2e
      # - build
      # - unit
      # - e2e:
      #     requires:
      #       - build
      #       - unit
      # - deploy:
      #     requires:
      #       - e2e
      #     filters:
      #       branches:
      #         only:
      #           master